version: "3"
services:

  db:
    image: postgres
    container_name: db_welcome
    networks:
      - backend
  
  web:
    build: .
    container_name: web_welcome
    command: gunicorn mann.wsgi:application --bind 0.0.0.0:8000 
    volumes:
      - .:/copycat  
    networks:
      - backend
    environment:
      - SQL_USER:postgres
      - SQL_PASSWORD:postgres
    depends_on:
      - db

  nginx:
    image: nginx:latest
    container_name: nginx_welcome
    volumes:
      - ./configs/:/etc/nginx/conf.d
      - static:/copycat/static
      - media:/copycat/media
    networks:
      - backend
    ports:
      - "80:80"
    depends_on:
      - web
  pureftpd:
    image: vimagick/pure-ftpd
    ports:
      - "21:21"
    volumes:
      - ./data/ftpuser:/home/ftpuser
      - ./data/pure-ftpd:/etc/pure-ftpd
    privileged: true
    restart: always

networks:
  backend:
    driver: bridge  