version: "3"
services:

  db:
    image: postgres
    container_name: db_welcome
    networks:
      - backend
  
  web:
    build: .
    container_name: web_welcome
    command: python manage.py runserver 0.0.0.0:8000 
    volumes:
      - .:/copycat
    ports:
      - "88:8000" 
    networks:
      - backend
    environment:
      - SQL_USER:postgres
      - SQL_PASSWORD:postgres
    depends_on:
      - db

 

networks:
  backend:
    driver: bridge  