# Generated by Django 2.2.1 on 2019-05-15 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='nan', max_length=20)),
                ('lastname', models.CharField(default='nan', max_length=20)),
                ('confirmation', models.BooleanField(default=False)),
                ('sex', models.CharField(default='nan', max_length=10)),
                ('email', models.CharField(default='nan', max_length=20)),
                ('password', models.CharField(default='nan', max_length=20)),
            ],
        ),
    ]
