# Generated by Django 2.2.1 on 2019-05-16 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='born_date',
            field=models.DateField(null=True),
        ),
    ]
