# Generated by Django 2.2.1 on 2019-06-02 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0003_auto_20190602_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(default='nan', max_length=200),
        ),
    ]
