# Generated by Django 2.2.7 on 2019-11-09 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0004_auto_20190602_0157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='confirmation',
        ),
    ]
