# Generated by Django 2.2.2 on 2019-06-17 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='album',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
