# Generated by Django 2.2.7 on 2019-11-09 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0003_song_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='image',
        ),
        migrations.AddField(
            model_name='song',
            name='file_data',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
